version: '3'

services:
  server:
    build:
      context: .
    image: registry.balcia.com/balcia_dev/java/rest-dropwizard
    ports:
      - '8080:8080'
      - '8081:8081'
      - '8443:8443'
