appName: Kotlin REST WS example

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres_234
  url: jdbc:postgresql://db/postgres
  properties:
    charSet: UTF-8
  validationQuery: "SELECT 1"

swagger:
  resourcePackage: com.balcia.binsy.ws.resources
