appName: Kotlin REST WS example

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO

database:
  driverClass: oracle.jdbc.OracleDriver
  user: bta
  password: bta_234
  url: jdbc:oracle:thin:@localhost:1521/binsy1
  properties:
    charSet: UTF-8
  validationQuery: "SELECT * from dual"

swagger:
  resourcePackage: com.balcia.binsy.ws.resources
